import React from "react";
import { Inter } from "next/font/google";
import Sidebar from "./_components/Sidebar";

import "@/app/_styles/global.css";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className=" flex">
          <Sidebar />
          <main className="bg-[#131416] w-full ">
            <div className="max-w-6xl mx-auto relative pt-24">
              <Header />
              <section>{children}</section>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
